### ISSUE TITLE
Feature file - milestone percentage out of getTransactionsToApprove

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri-regression#19]
### Description
Extend the feature files so that we cover a scenario for measuring the creation of blowballs - Milestone percentage out of getTransactionsToApprove - <5%? 

Does it only happen when the cache is full/after multiple calls to GTTA?

### Motivation
Cover the possibility of creating regressions where blowballs form around milestone (not just in theory). 

### Issues
1. When we found an invalid tip, we returned to the previous step. A milestone surround by a lot of invalid TXs was then too often picked up as the tip. 

2. When checking validity of transaction on GTTA, we also inserted them into a cache of already invalid TXs. And some transactions got inserted into the cache even though they were valid. On subsequent calls to GTTA, we disregarded these because they were in the cache. This piled up the amount of invalid transactions. 

### How to test for this
1. Generate a database where we have lots of invalid transactions (e.g., incorrent spending TX with unbalanced output) around a milestone.
2. Create databases according to the two scenarios. For the second one, it should be a DB with a side-tangle. 
3. Call GTTA 1000x and check that out of the returned tips, <5% correspond to the coordinator address (are milestones).   
4. The first scenario should fail on 1.4.2.4 (we think(some of us))
5. The second scenario should fail on 1.5.0

**Comment by DyrellC** [comment]
Until I have a tool for building a db with a side tangle of its own, i'll be using `db-552031` for the `1.5.0` node (the `1.4.2` node will have to wait until I have a db from pre release. `dbfile.iota.org` doesn't have any db's from prior to the release currently). 

In order to run the scenarios, each node's configuration will be set up manually (for now) by entering the configuration values into the `output.yml` file directly. GTTA will be called 1000x on these nodes, and an api call for `findTransactions` using the coo address will return the milestones. The results will be compared with the milestones to determine the percentage of returned milestones from GTTA.

**Comment by GalRogozinski** [comment]
The second scenario should also fail on 1.5.2

**Comment by GalRogozinski** [comment]
The change ^ is because it is when the walk validator cache was added.

**Comment by DyrellC** [comment]
The results of the tests were as follows: 

1.4.2.4
In order to simulate the issue outlined in scenario 1, a local `1.4.2.4` node was set up. Milestones, valid transactions and invalid transactions were issued to the node to build a db. Once the tests were conducted, the assertion at the end failed every time. After multiple tests, the average milestone reference percentage was over 85%. 

1.5.0 - 1.5.2
In order to simulate the issue outlined in scenario 2, local `1.5.0` through `1.5.2` nodes were set up. Milestones, valid transactions, invalid transactions and a side tangle were issued to build the db's. On occasion the test would fail, but in most cases the results were around 3% - 4%. 

1.5.3
For these tests, a local `1.5.3` node was set up. Milestones, valid transactions, invalid transactions and a side tangle were issued to build the db. In most cases, none of the transactions returned were milestones. In the tests that returned milestones, the return perentage was under 2%.

**Comment by DyrellC** [comment]
The final db's used in the tests will be uploaded to an s3 bucket and included in the `config.yml` file to demonstrate the failure of the tests in `v1.4.2.4` through `v1.5.2`. A poisoned cache results in failure in `1.5.0` through `1.5.2` and the presence of numerous invalid transactions results in failure in `1.4.2.4`.
